[package]
authors.workspace    = true
description          = "Adapter for interacting with cosmoslogy:starship via cw-orch"
edition.workspace    = true
license.workspace    = true
name                 = "cw-orch-starship"
repository.workspace = true
version              = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest    = { version = "0.12.5", features = ["json"] }
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
# Serde yaml deprecated
cosmwasm-std       = { workspace = true }
ibc-chain-registry = { workspace = true }
ibc-relayer-types  = { workspace = true }
thiserror          = "1.0.63"
yaml-rust2         = "0.8"

cw-orch-core   = { workspace = true }
cw-orch-daemon = { workspace = true }
tokio          = { workspace = true }

env_logger    = "0.11"
log.workspace = true
url           = "2.5.2"

k8s-openapi = { version = "0.22.0", features = ["latest"] }
kube        = { version = "0.93.1", features = ["runtime", "derive", "ws"] }
