[package]
authors.workspace    = true
description          = "An interchain intergration crate for interacting with actual chain nodes (via gRPC)"
edition.workspace    = true
license.workspace    = true
name                 = "cw-orch-interchain-daemon"
repository.workspace = true
version              = "0.10.0"

[lib]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch-core   = { workspace = true }
cw-orch-daemon = { workspace = true }

tokio = { workspace = true }

async-recursion   = "1.1.1"
base64            = "0.22.1"
cosmrs            = { workspace = true }
cosmwasm-schema   = "2.1.3"
derive_builder    = "0.20.0"
diff-struct       = "0.5.3"
futures           = "0.3.30"
futures-util      = "0.3.30"
ibc-relayer-types = { workspace = true }
log               = "0.4.22"
log4rs            = "1.3.0"
serde_json        = { workspace = true }
thiserror         = "1.0.63"
tonic             = { workspace = true }

cosmwasm-std            = { workspace = true }
cw-orch-interchain-core = { workspace = true, features = ["daemon"] }
cw-orch-starship        = { workspace = true }
dialoguer               = "0.11.0"

[dev-dependencies]

anyhow             = { workspace = true }
cw-orch            = { workspace = true, features = ["daemon"] }
cw-orch-interchain = { path = "../../../cw-orch-interchain", features = ["daemon"] }
pretty_env_logger  = "0.5.0"
