[package]
authors.workspace    = true
description          = "Adapter for interacting with cw-multi-test via the cw-orchestrator tool"
edition.workspace    = true
license.workspace    = true
name                 = "cw-orch-clone-testing"
repository.workspace = true
version              = "0.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }

cw-orch-core   = { workspace = true }
cw-orch-daemon = { workspace = true }
cw-orch-mock   = { workspace = true }

# clone-cw-multi-test = { version = "0.7.0" }
# clone-cw-multi-test = { path = "../../../cw-multi-test-fork", features = ["cosmwasm_1_2", "tokenfactory", "staking"] }
clone-cw-multi-test = { git = "https://github.com/abstractsdk/cw-multi-test-fork", branch = "adapt_for_local_execution", features = ["cosmwasm_1_2", "stargate", "tokenfactory", "staking"] }

anyhow    = { workspace = true }
cw-utils  = { workspace = true }
itertools = "0.12.0"
log       = { workspace = true }
serde     = { workspace = true }
sha2      = "0.10.8"
tokio     = { workspace = true }
tonic     = { workspace = true }

[dev-dependencies]
cosmwasm-schema = "2.0.0"
speculoos       = { workspace = true }

cw20      = { version = "2.0.0" }
cw20-base = { version = "2.0.0" }

counter-contract  = { path = "../../contracts-ws/contracts/counter" }
cw-orch           = { path = "../../cw-orch", features = ["daemon"] }
env_logger        = "0.10.0"
pretty_env_logger = "0.5.0"
