permissions:
  contents: read
on:
  push:
    branches: [main]
name: test
env:
  CODECOV_TOKEN: 62fac3fe-498a-4449-a00d-a9b30b443acf
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: ubuntu / stable / coverage
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Free up disk space on runner
        run: |
          df -h
          rm -rf /usr/share/dotnet/
          sudo apt-get remove -y 'php.*' || true
          sudo apt-get remove -y '^dotnet-.*' || true
          sudo apt-get remove -y azure-cli firefox powershell mono-devel || true
          sudo apt-get autoremove -y || true
          sudo apt-get clean || true
          df -h
        shell: bash
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo llvm-cov
        run: cargo llvm-cov --locked --all-features --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
